### ISSUE TITLE
Compile error: gk_lorawan_keys.project.cpp: No such file or directory

### ISSUE THREAD

**Issue by svelmurugan92** [mcci-catena/Catena4410-Sketches#6]
While build the Catena4450m101_Sensor faced some minor issues. Listed it below.

1. gk provision key not found
Issue :

> Arduino: 1.8.2 (Windows 7), Board: "Adafruit Feather M0"
> 
> C:\Users\velmurugan\Documents\Arduino\libraries\Catena4410-Arduino-Library\src\lib\Catena4410_gk_lorawan_keys.cpp:120:90: fatal error: ../../../catena-lorawan-provisioning/extra/gk_lorawan_keys.project.cpp: No such file or directory
> 
> #include "../../../catena-lorawan-provisioning/extra/gk_lorawan_keys.project.cpp"
>                                                               ^
> compilation terminated.`

My changes: 
Looks like these are needed for 4410 not for 4450. 
So, I Remove/rename Catena4420_gk_lorawan_keys.cpp and Catena4410_gk_lorawan_keys.cpp. 
To prevent it from compiling. (I know, There is some better way to do that).

**Comment by terrillmoore** [comment]
This is really two issues. I will split this up.

**Comment by terrillmoore** [comment]
See issue https://github.com/mcci-catena/Catena4410-Arduino-Library/issues/1 -- this is really a problem with that library.

**Comment by terrillmoore** [comment]
Closed by https://github.com/mcci-catena/Catena4410-Arduino-Library/commit/cb2a0f4cf1b6287010d90954ad61aebd4a21e53b
